version: "3"
services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
    - 80:80
    - 443:443
    volumes:
    - $PWD/nginx/default.conf:/etc/nginx/conf.d/default.conf
    - $PWD:/usr/share/nginx/html
    - ssl:/etc/ssl
  php:
    image: php:7.1-fpm
    container_name: php
    volumes:
    - $PWD:/var/www/html
volumes:
  ssl:
